import React, { useState } from "react";
import { useEnergy } from "../context/EnergyContext";
import { IconBrain, IconCpu } from "../components/NcIcons";

const PRIORITY_CFG = {
  critical: { color:"#F43F5E", bg:"rgba(244,63,94,0.08)",  border:"rgba(244,63,94,0.2)",  label:"Critical"  },
  high:     { color:"#F59E0B", bg:"rgba(245,158,11,0.08)", border:"rgba(245,158,11,0.2)", label:"High"      },
  medium:   { color:"#818CF8", bg:"rgba(99,102,241,0.08)", border:"rgba(99,102,241,0.2)", label:"Medium"    },
  positive: { color:"#10B981", bg:"rgba(16,185,129,0.08)", border:"rgba(16,185,129,0.2)", label:"Positive"  },
  info:     { color:"#06B6D4", bg:"rgba(6,182,212,0.08)",  border:"rgba(6,182,212,0.2)",  label:"Info"      },
};

function InsightCard({ insight, index }) {
  const [expanded, setExpanded] = useState(false);
  const s = PRIORITY_CFG[insight.priority] || PRIORITY_CFG.info;
  return (
    <div className="anim-fade-up" style={{ animationDelay:`${index*0.06}s`,opacity:0 }}>
      <div onClick={() => setExpanded(e => !e)}
        style={{ padding:"18px 20px",borderRadius:14,background:s.bg,border:`1px solid ${s.border}`,cursor:"pointer",transition:"all 0.22s" }}
        onMouseEnter={e => { e.currentTarget.style.transform="translateY(-1px)"; e.currentTarget.style.boxShadow=`0 6px 24px ${s.color}18`; }}
        onMouseLeave={e => { e.currentTarget.style.transform="translateY(0)"; e.currentTarget.style.boxShadow="none"; }}
      >
        <div style={{ display:"flex",gap:14,alignItems:"flex-start" }}>
          <div style={{ width:44,height:44,borderRadius:12,background:`${s.color}15`,border:`1.5px solid ${s.color}45`,display:"flex",alignItems:"center",justifyContent:"center",fontSize:22,flexShrink:0,boxShadow:`0 4px 14px ${s.color}18` }}>
            {insight.icon}
          </div>
          <div style={{ flex:1 }}>
            <div style={{ display:"flex",alignItems:"center",gap:8,marginBottom:5,flexWrap:"wrap" }}>
              <span style={{ fontFamily:"Sora,sans-serif",fontWeight:700,fontSize:14.5,color:s.color }}>{insight.title}</span>
              <span style={{ fontSize:10,padding:"2px 8px",borderRadius:10,background:`${s.color}18`,color:s.color,fontWeight:700 }}>{insight.tag}</span>
              <span style={{ fontSize:10,padding:"2px 8px",borderRadius:10,background:"rgba(255,255,255,0.05)",color:"var(--text2)",fontWeight:600,marginLeft:"auto" }}>{s.label} Priority</span>
            </div>
            <p style={{ fontSize:13.5,color:"var(--text2)",lineHeight:1.65,margin:0 }}>{insight.text}</p>
          </div>
        </div>
        {expanded && (
          <div style={{ marginTop:16,paddingTop:16,borderTop:`1px solid ${s.color}18` }}>
            <div style={{ fontSize:12.5,color:"var(--text2)",lineHeight:1.75 }}>
              <strong style={{ color:s.color,display:"block",marginBottom:6 }}>What this means for you:</strong>
              This insight was generated by analyzing your current behavioral patterns, recent stress indicators, recovery quality, and historical emotional data. The AI agent updates its analysis continuously as your inputs change.
            </div>
            <div style={{ marginTop:12,display:"flex",gap:8,flexWrap:"wrap" }}>
              <div style={{ padding:"8px 14px",borderRadius:9,background:"rgba(255,255,255,0.04)",border:"1px solid var(--border)",fontSize:12,color:"var(--text2)" }}>
                🎯 Recommended: Update your metrics in Settings for more accurate analysis
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}

function PatternCard({ icon, label, value, desc, color }) {
  return (
    <div className="glass" style={{ padding:"18px 20px" }}>
      <div style={{ display:"flex",alignItems:"center",gap:10,marginBottom:10 }}>
        <div style={{ width:36,height:36,borderRadius:10,background:`${color}15`,border:`1.5px solid ${color}40`,display:"flex",alignItems:"center",justifyContent:"center",fontSize:18 }}>
          {icon}
        </div>
        <span style={{ fontFamily:"Sora,sans-serif",fontWeight:600,fontSize:13,color:"var(--text)" }}>{label}</span>
      </div>
      <div style={{ fontFamily:"Sora,sans-serif",fontWeight:800,fontSize:28,color,marginBottom:4 }}>{value}</div>
      <div style={{ fontSize:12,color:"var(--text2)",lineHeight:1.5 }}>{desc}</div>
    </div>
  );
}

export default function AIInsights() {
  const { metrics, aiInsights, aiMemory, hourly, energyScore, burnoutRisk } = useEnergy();
  const [filter, setFilter] = useState("all");
  const h = Array.isArray(hourly) ? hourly : [];
  const filters = ["all","critical","high","medium","positive","info"];
  const filtered = filter === "all" ? aiInsights : aiInsights.filter(i => i.priority === filter);

  const avgScore   = h.length > 0 ? Math.round(h.slice(0,24).reduce((a,x) => a+(x.score||0),0)/Math.min(24,h.length)) : energyScore;
  const peakScore  = h.length > 0 ? Math.max(...h.slice(0,24).map(x => x.score||0)) : energyScore;
  const avgRisk    = h.length > 0 ? Math.round(h.slice(0,24).reduce((a,x) => a+(x.risk||0),0)/Math.min(24,h.length)) : burnoutRisk;
  const streakDays = aiMemory?.streaks?.highStress || 0;

  return (
    <div className="page">
      <div className="page-pad">

        {/* Header */}
        <div className="glass anim-fade-up" style={{ padding:"24px 28px",background:"linear-gradient(135deg,rgba(99,102,241,0.1),rgba(139,92,246,0.07))",border:"1px solid rgba(99,102,241,0.2)" }}>
          <div style={{ display:"flex",alignItems:"center",gap:14,marginBottom:12 }}>
            <IconBrain size={46}/>
            <div>
              <div style={{ fontFamily:"Sora,sans-serif",fontWeight:700,fontSize:20,color:"var(--text)" }}>Agentic AI Observations</div>
              <div style={{ fontSize:13,color:"var(--text2)",marginTop:2 }}>Dynamically generated from your behavioral patterns and emotional history</div>
            </div>
            <div style={{ marginLeft:"auto",display:"flex",alignItems:"center",gap:6,padding:"7px 14px",borderRadius:9,background:"rgba(16,185,129,0.1)",border:"1px solid rgba(16,185,129,0.2)" }}>
              <div className="dot-live"/>
              <span style={{ fontSize:12,color:"#10B981",fontWeight:600 }}>Live Analysis</span>
            </div>
          </div>
          <p style={{ fontSize:13.5,color:"var(--text2)",lineHeight:1.7,margin:0 }}>
            The AI engine continuously observes your mood entries, stress patterns, social load, sleep quality, and recovery behaviors.
            Unlike static recommendations, these insights evolve as your behavioral data accumulates over time.
            {h.length > 0 && ` Currently analyzing ${h.length} hourly data points.`}
          </p>
        </div>

        {/* Pattern summary */}
        <div style={{ display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:14 }}>
          <PatternCard icon="📊" label="Avg Energy Score"   value={avgScore}         desc="Average over tracked hours"  color="#818CF8"/>
          <PatternCard icon="🔥" label="Avg Burnout Risk"   value={`${avgRisk}%`}    desc="Risk level trend today"      color={avgRisk>=60?"#F43F5E":"#F59E0B"}/>
          <PatternCard icon="📅" label="High Stress Streak" value={`${streakDays}d`} desc="Consecutive elevated stress" color={streakDays>=3?"#F43F5E":"#10B981"}/>
          <PatternCard icon="⚡" label="Peak Score Today"   value={peakScore}         desc="Best energy point recorded"  color="#10B981"/>
        </div>

        {/* Filter tabs */}
        <div style={{ display:"flex",gap:8,flexWrap:"wrap" }}>
          {filters.map(f => (
            <button key={f} onClick={() => setFilter(f)}
              style={{ padding:"7px 16px",borderRadius:9,border:"1px solid",fontSize:12.5,fontWeight:600,cursor:"pointer",transition:"all 0.18s",
                background: filter===f ? "rgba(99,102,241,0.15)" : "rgba(255,255,255,0.03)",
                borderColor: filter===f ? "rgba(99,102,241,0.35)" : "var(--border)",
                color: filter===f ? "#818CF8" : "var(--text2)" }}>
              {f.charAt(0).toUpperCase() + f.slice(1)}
            </button>
          ))}
        </div>

        {/* Insights list */}
        <div style={{ display:"flex",flexDirection:"column",gap:10 }}>
          {filtered.length === 0 ? (
            <div className="glass" style={{ padding:"40px",textAlign:"center" }}>
              <div style={{ display:"flex",justifyContent:"center",marginBottom:12 }}><IconBrain size={48}/></div>
              <div style={{ fontSize:14,color:"var(--text2)" }}>No insights in this category right now.</div>
            </div>
          ) : filtered.map((ins,i) => <InsightCard key={i} insight={ins} index={i}/>)}
        </div>

        {/* AI Memory note */}
        <div className="glass" style={{ padding:"18px 22px",borderColor:"rgba(99,102,241,0.15)" }}>
          <div style={{ display:"flex",gap:12,alignItems:"flex-start" }}>
            <IconCpu size={32}/>
            <div>
              <div style={{ fontFamily:"Sora,sans-serif",fontWeight:600,fontSize:13,color:"var(--text)",marginBottom:4 }}>About the AI Engine</div>
              <p style={{ fontSize:12.5,color:"var(--text2)",lineHeight:1.7,margin:0 }}>
                NeuroCalm's agentic AI engine analyzes multi-dimensional behavioral signals including stress trends, sleep patterns, interaction pressure, recovery consistency, and mood volatility.
                It maintains memory across sessions to detect recurring triggers and patterns that single-session analysis would miss.
                The longer you use NeuroCalm, the more personalized and accurate the insights become.
              </p>
            </div>
          </div>
        </div>

      </div>
    </div>
  );
}
